version: 0.0
os: linux
files:
  - source: /
    destination: /data/myNodejsApp
    runas: ec2-user

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: ec2-user

  AfterInstall:
    - location: scripts/install.sh
      timeout: 100
      runas: ec2-user

  ApplicationStart:
    - location: /data/myNodejsApp/scripts/start.sh
      timeout: 100
      runas: ec2-user